### ISSUE TITLE
Error after upgrading to v 0.10.0

### ISSUE THREAD

**Issue by t1u1** [extmkv/ResourcePlaceholdersPlugin#4]
The upgrade to Gradle and AGP was recommended by Android Studio 2023.2.1 (latest stable).

I also updated this plugin to 0.11.2.

But I get the following error after these updates:

```
Execution failed for task ':app:resourcePlaceholdersForAppDebug'.
> Querying the mapped value of list(interface java.util.Collection, org.gradle.api.internal.provider.AbstractCollectionProperty$CollectingSupplier@3464e8) before task ':app:resourcePlaceholdersForAppDebug' has completed is not supported

```

**Comment by t1u1** [comment]
Actually, after reverting back the Gradle to 8.2 and AGP to 8.2.1, I still see the error.

So the update of this plugin to 0.11.2 is causing the problem. Updated the issue title accordingly.

The exact version which introduces this problem is 0.10.0.

**Comment by halfninja** [comment]
Seeing this with Gradle 8.11.1 + AGP 8.9.0.

Error with `--stacktrace` - this actually seems to be at a logging line, so I'm wondering if we could do without some of the logging if it resolves the issue (EDIT: unfortunately not - it still needs to call this to actually do the replacement)

```
org.gradle.api.InvalidUserCodeException: Querying the mapped value of list(interface java.util.Collection, item(list(interface org.gradle.api.file.Directory, map(provider(?)))) + item(list(interface org.gradle.api.file.Directory, map(provider(?)))) + item(list(interface org.gradle.api.file.Directory, map(property(org.gradle.api.file.Directory, property(org.gradle.api.file.Directory, property(org.gradle.api.file.Directory, map(org.gradle.api.file.Directory flatmap(provider(task 'generateDebugResValues', class com.android.build.gradle.tasks.GenerateResValues)) check-type()))))))) + item(list(interface org.gradle.api.file.Directory, map(flatmap(provider(task 'resourcePlaceholdersForDebug', class de.timfreiheit.plugin.resourceplaceholders.ResourcePlaceholdersTask))))) + item(list(interface org.gradle.api.file.Directory, and(provider(java.util.Set), provider(?))))) before task ':app:generateDebugResValues' has completed is not supported
        at org.gradle.api.internal.provider.TransformBackedProvider.lambda$beforeRead$0(TransformBackedProvider.java:98)
        at org.gradle.api.internal.provider.ValueSupplier$TaskProducer.visitProducerTasks(ValueSupplier.java:128)
        at org.gradle.api.internal.provider.ValueSupplier$PlusProducer.visitProducerTasks(ValueSupplier.java:156)
        at org.gradle.api.internal.provider.ValueSupplier$PlusProducer.visitProducerTasks(ValueSupplier.java:155)
        at org.gradle.api.internal.provider.ValueSupplier$PlusProducer.visitProducerTasks(ValueSupplier.java:155)
        at org.gradle.api.internal.provider.ValueSupplier$ValueProducer.visitContentProducerTasks(ValueSupplier.java:73)
        at org.gradle.api.internal.provider.TransformBackedProvider.beforeRead(TransformBackedProvider.java:95)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:80)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:80)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:100)
        at de.timfreiheit.plugin.resourceplaceholders.ResourcePlaceholdersTask.action(ResourcePlaceholdersTask.kt:46)
```
